personal data.0.name = "Dart Veider"
personal data.0.age = 102
personal data.0.relatives.son = "Luk"
personal data.0.relatives.doughtier = "Leya"
personal data.0.address = "Star Wars"
personal data.0.hobby = "evil"
phone = "nokia"
group = 12
